; Xdebug 2
xdebug.remote_enable=1
xdebug.remote_autostart=0
xdebug.remote_host=host.docker.internal
xdebug.remote_port=9003

; Xdebug 3
xdebug.mode=debug,develop
xdebug.start_with_request=trigger
xdebug.client_host=host.docker.internal
xdebug.client_port=9003
